hardware_node:
  ros__parameters:
    vesc_can_interface: "can_front_vesc"
    vesc_motor_ids: [3, 4]
    vesc_operate_modes: ["position", "position"] #current, speed, position
    vesc_gear_ratio: [1.0, 1.0]
    vesc_motor_gear_ratio: [35.0, 35.0]
    vesc_pole_pairs: [4, 4]

    vesc_current_min: [-0.5, -0.5] #A
    vesc_current_max: [0.5, 0.5]

    vesc_speed_min: [-25.0, -25.0] #RPM
    vesc_speed_max: [25.0, 25.0]
    vesc_speed_deadzone: [5.0, 5.0]

    vesc_position_min: [-75.0, -75.0] #degree
    vesc_position_max: [75.0, 75.0]
    vesc_position_zero_offset: [0.0, 0.0]

