joy_node:
  ros__parameters:
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_joystick:
  ros__parameters:
    rearbot_cmd_vel_max_lin: 0.2
    rearbot_cmd_vel_max_ang: 1.0

    frontbot_cmd_vel_max_lin: 0.2
    frontbot_cmd_vel_max_ang: 1.0

    multibot_cmd_vel_max_lin: 0.2
    multibot_cmd_vel_max_ang: 0.2

    linear_axis_index: 1
    angular_axis_index: 3

    x_button_index: 0
    ps_button_index: 10

    home_button_index: 1
    cart_docking_button_index: 2
    robot_docking_button_index: 3

    cart_count_zero_button_index: 4
    cart_count_two_button_index: 5

    scenario_sequence_axis_index: 6

    gripper_toggle_button_index: 9