/**:
  ros__parameters:
    mightyzap_serial_port: "/dev/rs485_front_mightyzap"
    mightyzap_baudrate: 57600

    mightyzap_command_timeout_ms: 2000

    mightyzap_actuator_id: 0

    mightyzap_position_min: 0
    mightyzap_position_max: 4095
    mightyzap_position_tolerance: 20

    mightyzap_initial_position: 2850

    mightyzap_speed_min: 0
    mightyzap_speed_max: 1023

    mightyzap_initial_speed: 600

    mightyzap_safe_position: 2850

    mightyzap_operating_rate_limit: 600

    mightyzap_force_on_at_start: true