/**:
  ros__parameters:
    rmd_can_interface: "can_front_rmd"
    rmd_motor_ids: [1, 2]
    rmd_operate_modes: ["speed", "speed"]   # current, speed, position
    rmd_gear_ratio: [3.0, 3.0]

    rmd_speed_min: [-90.0, -90.0] # RPM
    rmd_speed_max: [90.0, 90.0]
    rmd_speed_deadzone: [5.0, 5.0]

    vesc_can_interface: "can_front_vesc"
    vesc_motor_ids: [3, 4]
    vesc_operate_modes: ["position", "position"] #current, speed, position
    vesc_gear_ratio: [1.0, 1.0]
    vesc_motor_gear_ratio: [35.0, 35.0]
    vesc_pole_pairs: [4, 4]

    vesc_position_min: [-60.0, -60.0] #degree
    vesc_position_max: [60.0, 60.0]
    vesc_position_zero_offset: [295.0, 287.0]

    front_rmd_motor_ids: [1, 2]
    front_vesc_motor_ids: [3, 4]

    front_wheel_radius: 0.0635 # m
    front_track_width: 0.265 # m
    
    wheel_base: 0.480 # m